---
name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: 'Make (and upload) ZIP file(s)'
        uses: oracle-devrel/action-release-zip-maker@v0.5
        id: zip_maker
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


  latest-release:
    name:  "Latest Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Latest Build"
          files: |
            LICENSE.txt
            *.zip
