---
name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  latest-release:
    name:  "Latest Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Latest Build"
          files: |
            LICENSE.txt
            *.*
